### ISSUE TITLE
Proposed Topic: An accelerated AI platform for heart disease diagnosis 

### ISSUE THREAD

**Issue by gaojinghua** [open-heterogeneous-computing-framework/conference#1]
### Topic Title
An accelerated AI platform for heart disease diagnosis 

### Abstract
Recently, deep learning technologies offer ways to diagnose heart diseases automatically which may benefit millions of people in rural areas.
In this talk, we will first introduce the medical background of heart disease diagnosis and what's the challenges using the AI platform for remote healthcare. Then, we will elaborate on our heart diseases diagnosis platform in details. This section includes the infrastructure design, the introduction of the diagnosis process and the dynamic training process. Next, we will present the preliminary screening models at the edge side and classification models in the cloud. The whole talk will elaborate on how to accelerate the infrastructure as well as the models both at the edge and in the cloud. (GPU + Movidius)

### Related Upstream Open Source Projects
OpenStack Nova, OpenStack Cyborg, Kubernetes

### Category 
* Accelerator Hardware
* Cloud Platform Management Support For Accelerators
* Applications With Accelerator Support (AI, 5G, Edge/IoT, HPC, Quantum Computing, Neuromorphic Computing, etc)

### Speaker Bio (no more than 2 people)
Jinghua Gao, Staff Researcher, Lenovo Research
Got involved in OpenStack for 5+ years and Kubernetes for 2+ years. Mainly focus on network management. Interests include DPDK technology, user-space TCP/IP stack, load-balance and so on. Recent work is related to intelligent traffic analysis and hardware acceleration.

### Speaker email
Jinghua Gao(gaojh4@gmail.com, 419546439@qq.com)

**Comment by hannibalhuang** [comment]
Move to part of the [unconference discussion](https://github.com/open-heterogeneous-computing-framework/conference/blob/master/2019-events.md)
