### ISSUE TITLE
A heterogeneous hardware management  solution for 5G Ultra Reliable & Low Latency Network

### ISSUE THREAD

**Issue by YumengBao** [open-heterogeneous-computing-framework/conference#2]
### Topic Title
A heterogeneous hardware management  solution for 5G Ultra Reliable & Low Latency Network
### Abstract
5G Ultra Reliable & Low Latency Network technology is quite important for our future lives. Imagine a scenario of Network for autopilot, where high precision time synchronization between wireless sensor networks is required to ensure safe driving.  However, there is few such hardware which supports time synchronization between multiple VMs and meets the 5G resolution requirement in the industry at this moment. 
This presentation will introduce a device, named High Precision Time Synchronization card (Use HPTS card for abbreviation), which handles the above problem. We will present the architecture of this solution on both the data panel and management panel. And OpenStack Cyborg will provide the lifecycle management in this solution, including discovering, publishing in Nova placement, attaching devices to VMs, termination, etc.
### Related Upstream Open Source Projects
OpenStack Cyborg, OpenStack Nova
### Category (at least choose one of the following)
* Cloud Platform Management Support For Accelerators
* Applications With Accelerator Support (AI, 5G, Edge/IoT, HPC, Quantum Computing, Neuromorphic Computing, etc)
### Speaker Bio (no more than 2 people)
Yumeng Bao
Yumeng is a software engineer from ZTE Corporation. She has contributed in OpenStack since 2016 and served as a core contributor in OpenStack Watcher project, also a core reviewer in Cyborg project.
### Speaker email
Yumeng Bao (yumeng_bao@yahoo.com, bao.yumeng@zte.com.cn)

**Comment by hannibalhuang** [comment]
Move to part of the [unconference discussion](https://github.com/open-heterogeneous-computing-framework/conference/blob/master/2019-events.md)
