### ISSUE TITLE
TLS offloading solution using heterogeneous HW management

### ISSUE THREAD

**Issue by xxinran** [open-heterogeneous-computing-framework/conference#3]
### Abstract
As we all know, the number of could end users is continously increasing in recent years, the workload in cloud also become heavier and heavier. Some accelerators has been added in cloud to offload the specific workload to ensure that CPU can work smoothly and efficiently. That's what we called "Heterogeneous computing" which refers to systems that use more than one kind of processor or cores. 

In this presentation, Cyborg project which aims to provide a general purpose management framework for acceleration resources (i.e. various types of accelerators such as GPU, FPGA, QAT etc.) will be introduced. The web service is one of the most popular application which run in cloud, for that reason, the use case where the Cyborg manages the QAT(QuickAssist Technology) card to do TLS offloading will also be introduced. QAT improves performance across applications and platforms. That includes symmetric encryption and authentication, asymmetric encryption, digital signatures, RSA, DH, and ECC, and lossless data compression.
### Related Upstream Open Source Projects
OpenStack Nova, OpenStack Cyborg
### Category (at least choose one of the following)
* Accelerator Hardware
* Cloud Platform Management Support For Accelerators
### Speaker Bio (no more than 2 people)
Xinran Wang, Intel
OpenStack upstream developer, currently working at Intel.
Core Reviewer and contributor of OpenStack Cyborg project, familiar with accelerators such as FPGA, QAT enabling and use cases in cloud. 
### Speaker email
xin-ran.wang@intel.com

**Comment by hannibalhuang** [comment]
Accepted as accelerator related [general topic](https://github.com/open-heterogeneous-computing-framework/conference/blob/master/2019-events.md)
