### ISSUE TITLE
A AI accelerator HDDL in Edge Computing

### ISSUE THREAD

**Issue by lvmxh** [open-heterogeneous-computing-framework/conference#4]
Abstract
Intel today introduced the Movidius Myriad X Vision processing Unit (VPU) which Intel is calling the first vision processing system-on-a-chip (SoC) with a dedicated neural compute engine to accelerate deep neural network inferencing at the network edge.
Intel also Unleashes a HDDL PCI card which integrates several Myriad VPUs for Edge Computing for AR/VR and AI scenarios.
In this talk, we will first introduce some details of Movidius VPU and HDDL, how it is managed in Edge cloud.  Also will give a demo to mange the HDDL and to use it for an AI inference.

Related Upstream Open Source Projects
OpenStack Nova, OpenStack Cyborg, Kubernetes

Category
Accelerator Hardware
Cloud Platform Management Support For Accelerators
Applications With Accelerator Support (AI, 5G, Edge/IoT, HPC, Quantum Computing, Neuromorphic Computing, etc)
Speaker Bio (no more than 2 people)
Shaohe Feng, Senior Software Engineers,  INTEL
Got involved in OpenStack for 5+ years and Kubernetes for 2+ years. Mainly focus on accelerator management. Interests include AI technology, hardware acceleration, network and so on. 

Speaker email
ShaoHe Feng(shaohe.feng@intel.com)

**Comment by hannibalhuang** [comment]
Move to part of the [unconference discussion](https://github.com/open-heterogeneous-computing-framework/conference/blob/master/2019-events.md)
