### ISSUE TITLE
A Lightweight Accelerator Management Framework in Edge

### ISSUE THREAD

**Issue by Horst-lgtm** [open-heterogeneous-computing-framework/conference#5]
### Topic Title
A Lightweight Accelerator Management Framework in Edge
### Abstract
As we all know, heterogeneous acceleration hardwares are difficult to use and complex to manage. In the cloud environment, projects such as cyborg are created as a unified heterogeneous resource management framework. Edge computing puts new demands on heterogeneous acceleration hardware usage and its management framework, such as lightweight , cloud-edge collaboration, etc.
This topic will show you how to tailor and transform the Cyborg project to meet the requirements of heterogeneous accelerators in the edge computing scenario.
### Related Upstream Open Source Projects
OpenStack Cyborg, OpenStack Nova, Kubernetes
### Category (at least choose one of the following)
* Accelerator Hardware
* Cloud Platform Management Support For Accelerators
* Applications With Accelerator Support (Edge/IoT)

### Speaker Bio
Zhenghao Wang, Staff Researcher, Lenovo Research.
OpenStack upstream developer.
Core Reviewer of OpenStack Cyborg project.

Got involved in OpenStack for 4+ years and Kubernetes for 2+ years. Responsible for the design and development of Lenovo OpenStack. Mainly focus on Nova, Keystone. Also interested in the accelerator. Recent work is related to edge computing and Virtualization.
### Speaker email
Zhenghao Wang (wangzhh0301@gmail.com, wangzh21@lenovo.com)

**Comment by hannibalhuang** [comment]
Move to part of the [unconference discussion](https://github.com/open-heterogeneous-computing-framework/conference/blob/master/2019-events.md)
