### ISSUE TITLE
Open Source: Accelerating Innovation in the AI Market

### ISSUE THREAD

**Issue by ibrahimhaddad** [open-heterogeneous-computing-framework/conference#6]
Abstract: 
Over the past two decades, open source software -- and its collaborative development model -- has disrupted multiple industries and technology sectors, including the Internet/web, telecom, and consumer electronics. Today, large scale open source projects in new technology sectors like blockchain and artificial intelligence are driving the next wave of disruption in an even broader span of verticals ranging from finance, energy and automotive to entertainment and government. 

In this session, Dr. Haddad will provide an overview of the advantages the open source software model brings to the artificial intelligence domain -- and the real-world impact it is having across industries. He will also discuss how the LF AI Foundation is supporting the development, harmonization, and acceleration of open source AI projects, and how this collaboration is leading to the creation of new opportunities for AI-focused open source communities and their supporting organizations. 

Duration:
20 mins

Speaker Bio:
http://www.ibrahimatlinux.com/about.html

Disclaimer:
Participation in OHCF event assumes no conflict with participation with other events held at OSS.

**Comment by hannibalhuang** [comment]
Accepted as colo [keynote speech](https://github.com/open-heterogeneous-computing-framework/conference/blob/master/2019-events.md)
