### ISSUE TITLE
大规模GPU虚拟化在讯飞云上的应用

### ISSUE THREAD

**Issue by xgoeforever** [open-heterogeneous-computing-framework/conference#7]
讯飞业务种类繁多，尤其在 AI 领域耕耘许久，算力的提升，也伴随着资源的疯狂增长。云平台承担着资源管理和降本增效的重担。如何构建平台化 AI 交付标准；在面临业务迅猛增长的情况下，如何经济有效地获取高性能异构计算能力；面对AI业务特有的异构资源，如果在任务管控中，实现异构资源的合理调度和复用。在解决这些问题中，经历多年的业务打磨，慢慢锤练出了一套成熟稳定的云平台，演生了一些在 AI 领域内特有的解决方案。本次将为大家带来大规模GPU虚拟化在讯飞的应用。

主要内容
1、讯飞业务的发展和本身特性；

2、GPU虚拟化演进和优化之路；

3、异构资源的虚拟化的挑战和实现；

4、业务在讯飞云上的实践。

听众受益
1、了解 AI 业务和资源管控的常见痛点和解决方案；

2、了解云平台在异构计算能力上的调度和复用方案；

3、了解异构资源虚拟化的几种实现方案；

4、了解人工智能业务在云上落地挑战以及解决方案。

**Comment by hannibalhuang** [comment]
Accepted for platform related topic
